app = 'brillioxe1'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

# إعدادات الخدمة
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

# إعدادات الماكينة
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
